# Allows to install updates automatically.
tap 'domt4/autoupdate'

# CLI Programms
brew 'youtube-dl'

# UI programms
cask 'balenaetcher'
cask 'filezilla'
cask 'flycut'
cask 'imageoptim'
# cask 'java'
# cask 'jetbrains-toolbox'
cask 'parsec'

# vim: set ft=ruby ts=2 sw=2 et:
