# Allows to install updates automatically.
tap 'domt4/autoupdate'

# Tools
brew 'youtube-dl'
brew 'axel'

cask 'flycut'
cask 'imageoptim'
cask 'menumeters'
# cask 'parsec'
cask 'tripmode'
cask 'vnc-viewer'

# Dev Tools
cask 'balenaetcher'
# cask 'java'
# cask 'jetbrains-toolbox'
# cask 'visual-studio'

# vim: set ft=ruby ts=2 sw=2 et:
