# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
#if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
#  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
#fi

# Loaded for all shells.

verbose Loading $fg[green]zshrc$reset_color

ZPLUG_LOADFILE="$DOTFILES/zsh/zplugs"

# Use extended_glob option for zplug subshells. We need to change it for zplug's use tags containing extended globs.
zstyle ":zplug:config:setopt" only_subshell extended_glob

zplug-init zplug-apply-unreleased-fixes
if [[ $? -ne 0 ]]; then
  return 1
fi

zplug-install

# Need to apply fixes once more after installing because zplug installs itself.
zplug-apply-unreleased-fixes

# Source plugins and add commands to the PATH.
zplug load ${ZSH_VERBOSE/true/--verbose}

# Clean up after ourselves.
undefine-startup-functions

# vim: set ft=zsh ts=2 sw=2 et:
export PATH="/usr/local/opt/curl/bin:$PATH"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
#[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# To customize prompt, run `p10k configure` or edit ~/.dotfiles/zsh/themes/lramm.zsh-theme.
[[ ! -f ~/.dotfiles/zsh/themes/lramm.zsh-theme ]] || source ~/.dotfiles/zsh/themes/lramm.zsh-theme
alias k=kubectl
complete -F __start_kubectl k

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
